"""Central, portable path configuration.

The experiment scripts write and read a tree of per-run output directories. In the
original research tree these were hard-coded to an absolute ``/notebooks/...`` path;
here they resolve relative to the repository root instead, and can be redirected with
environment variables so the same code runs unchanged on any machine.

Environment overrides
---------------------
``SP_OUTPUTS``  base directory for experiment outputs
                (default: ``<repo>/outputs/universality_pruning``)
``SP_FIGURES``  directory for generated report figures
                (default: ``<repo>/figures``)
"""
import os
from pathlib import Path

# <repo>/sparse_pretrain/paths.py  ->  parents[0]=sparse_pretrain, parents[1]=<repo>
PACKAGE_ROOT = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_ROOT.parent

# Experiment outputs (per-run directories: exhaustion runs, atom-peel runs, ...).
# Not version-controlled; regenerated by the pipeline. Override with $SP_OUTPUTS.
OUTPUTS = Path(os.environ.get("SP_OUTPUTS", REPO_ROOT / "outputs" / "universality_pruning"))

# Where plot scripts write report figures. Override with $SP_FIGURES.
FIGURES = Path(os.environ.get("SP_FIGURES", REPO_ROOT / "figures"))

# Curated name pools shipped with the package (inputs to the pronoun task splits).
NAME_POOLS = PACKAGE_ROOT / "data" / "name_pools"


def ensure_outputs() -> Path:
    """Create and return the experiment-outputs base directory."""
    OUTPUTS.mkdir(parents=True, exist_ok=True)
    return OUTPUTS


def ensure_figures() -> Path:
    """Create and return the figures directory."""
    FIGURES.mkdir(parents=True, exist_ok=True)
    return FIGURES
